Repository stolostron/console-chart, pull requests merged in 2021-03, with the labels that each got.

#107 #9783: update mch repo's default branch for auto-trigger build
  .travis.yml
Labels: approved, lgtm

#108 console server account watch rbac
  stable/console-chart/templates/console-clusterrole.yaml
  stable/console-chart/templates/console-deployment.yaml
Labels: approved, lgtm, tide/merge-method-squash

#109 fix copyright
  stable/console-chart/templates/_helpers.tpl
  stable/console-chart/templates/clusterimageset-clusterrole.yaml
  stable/console-chart/templates/clusterimageset-clusterrolebinding.yaml
  stable/console-chart/templates/console-clusterrole.yaml
  stable/console-chart/templates/console-clusterrolebinding.yaml
  stable/console-chart/templates/console-deployment.yaml
  stable/console-chart/templates/console-header-configmap.yaml
  stable/console-chart/templates/console-header-deployment.yaml
  stable/console-chart/templates/console-header-ingress-welcome.yaml
  stable/console-chart/templates/console-header-ingress.yaml
  stable/console-chart/templates/console-header-log-config.yaml
  stable/console-chart/templates/console-header-service.yaml
  stable/console-chart/templates/console-ingress.yaml
  stable/console-chart/templates/console-service.yaml
Labels: approved, lgtm

#110 Update clusterrole to watch discoveryconfig
  stable/console-chart/templates/console-clusterrole.yaml
Labels: lgtm

#111 Console ClusterRole added permissions
  stable/console-chart/templates/console-clusterrole.yaml
Labels: approved, lgtm

#112 update README
  README.md
Labels: approved, lgtm

#113 fix typo
  README.md
Labels: approved, lgtm

#116 update README based on template
  README.md
Labels: approved, lgtm

#114 Remove .travis.yml and add Github Actions
  .github/workflows/fast-forward.yml
  .github/workflows/helm-lint.yml
  .github/workflows/push-chart.yml
  .travis.yml
Labels: approved, lgtm

#117 add list verb needed for watches
  stable/console-chart/templates/console-clusterrole.yaml
Labels: approved, lgtm

#115 remove cert manager
  stable/console-chart/templates/hcmuiapi-certificate.yaml
  stable/console-chart/templates/hcmuiapi-deployment.yaml
  stable/console-chart/templates/hcmuiapi-service.yaml
Labels: approved, lgtm

#119 update ocp image list
  stable/console-chart/templates/img4.3.40-x86_64.yaml
  stable/console-chart/templates/img4.4.27-x86_64.yaml
  stable/console-chart/templates/img4.5.36-x86_64.yaml
  stable/console-chart/templates/img4.6.22-x86_64.yaml
  stable/console-chart/templates/img4.7.3-x86_64.yaml
Labels: lgtm

#122 remove welcome ingress as it is hosted in grc
  stable/console-chart/templates/console-header-ingress-welcome.yaml
Labels: approved, lgtm
